{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a7e12ff3-00ae-427c-b09b-87f9f6a9b052",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ================================\n",
    "# Fake User Detection – Streamlit App\n",
    "# ================================\n",
    "\n",
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import streamlit as st\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import LabelEncoder, StandardScaler\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.ensemble import RandomForestClassifier, IsolationForest\n",
    "from xgboost import XGBClassifier\n",
    "from sklearn.metrics import (\n",
    "    accuracy_score, precision_score, recall_score,\n",
    "    f1_score, roc_auc_score, confusion_matrix\n",
    ")\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import plotly.express as px\n",
    "import streamlit.components.v1 as components\n",
    "from haversine import haversine\n",
    "\n",
    "# ================================\n",
    "# PAGE CONFIG\n",
    "# ================================\n",
    "st.set_page_config(\n",
    "    page_title=\"🛡️ Fake User Detection Lab\",\n",
    "    layout=\"wide\",\n",
    "    page_icon=\"🛡️\"\n",
    ")\n",
    "\n",
    "st.title(\"🛡️ Fake User Analysis & Detection Dashboard\")\n",
    "st.write(\"End-to-end ML pipeline for detecting fake users in e-commerce systems.\")\n",
    "\n",
    "# ================================\n",
    "# LOAD DATA\n",
    "# ================================\n",
    "DATA_FILE = \"fakeuserdetection_ecommerce_data.csv\"\n",
    "\n",
    "if not os.path.exists(DATA_FILE):\n",
    "    st.error(f\"Dataset not found: {DATA_FILE}\")\n",
    "    st.stop()\n",
    "\n",
    "df = pd.read_csv(DATA_FILE)\n",
    "\n",
    "if \"LoginTimestamp\" in df.columns:\n",
    "    df[\"LoginTimestamp\"] = pd.to_datetime(df[\"LoginTimestamp\"], errors=\"coerce\")\n",
    "\n",
    "st.success(f\"Dataset loaded: {df.shape[0]} rows × {df.shape[1]} columns\")\n",
    "\n",
    "# ================================\n",
    "# FEATURE ENGINEERING\n",
    "# ================================\n",
    "st.header(\"🔧 Feature Engineering\")\n",
    "\n",
    "# IP clustering\n",
    "ip_counts = df.groupby(\"IPAddress\")[\"UserID\"].nunique().reset_index()\n",
    "ip_counts.columns = [\"IPAddress\", \"IPUserCount\"]\n",
    "df = df.merge(ip_counts, on=\"IPAddress\", how=\"left\")\n",
    "\n",
    "# Geo speed\n",
    "df = df.sort_values([\"UserID\", \"LoginTimestamp\"])\n",
    "df[\"TimeDiff\"] = df.groupby(\"UserID\")[\"LoginTimestamp\"].diff().dt.total_seconds() / 3600\n",
    "df[\"PrevLat\"] = df.groupby(\"UserID\")[\"Latitude\"].shift()\n",
    "df[\"PrevLon\"] = df.groupby(\"UserID\")[\"Longitude\"].shift()\n",
    "\n",
    "def geo_distance(row):\n",
    "    if pd.isna(row[\"PrevLat\"]) or pd.isna(row[\"PrevLon\"]):\n",
    "        return 0\n",
    "    return haversine(\n",
    "        (row[\"PrevLat\"], row[\"PrevLon\"]),\n",
    "        (row[\"Latitude\"], row[\"Longitude\"])\n",
    "    )\n",
    "\n",
    "df[\"Distance\"] = df.apply(geo_distance, axis=1)\n",
    "df[\"Speed\"] = df[\"Distance\"] / df[\"TimeDiff\"].replace(0, np.nan)\n",
    "df[\"Speed\"] = df[\"Speed\"].fillna(0)\n",
    "\n",
    "# Behavior ratios\n",
    "df[\"PurchaseToBrowseRatio\"] = df[\"Purchases\"] / df[\"BrowsingEvents\"].replace(0, np.nan)\n",
    "df[\"PurchaseToBrowseRatio\"] = df[\"PurchaseToBrowseRatio\"].fillna(0)\n",
    "\n",
    "# Device switching\n",
    "device_counts = df.groupby(\"UserID\")[\"DeviceType\"].nunique().reset_index()\n",
    "device_counts.columns = [\"UserID\", \"DeviceCount\"]\n",
    "df = df.merge(device_counts, on=\"UserID\", how=\"left\")\n",
    "\n",
    "# Encode categorical columns\n",
    "for col in [\"DeviceType\", \"Browser\"]:\n",
    "    le = LabelEncoder()\n",
    "    df[col] = le.fit_transform(df[col])\n",
    "\n",
    "st.success(\"Feature engineering completed\")\n",
    "\n",
    "# ================================\n",
    "# ML PIPELINE\n",
    "# ================================\n",
    "st.header(\"🧠 Machine Learning Models\")\n",
    "\n",
    "features = [\n",
    "    \"IPUserCount\", \"SessionDuration\", \"BrowsingEvents\", \"Purchases\",\n",
    "    \"AverageOrderValue\", \"CartAbandonmentRate\", \"Speed\",\n",
    "    \"PurchaseToBrowseRatio\", \"DeviceCount\", \"DeviceType\", \"Browser\"\n",
    "]\n",
    "\n",
    "target = \"IsFake\"\n",
    "\n",
    "X = df[features].fillna(0)\n",
    "y = df[target]\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.2, random_state=42, stratify=y\n",
    ")\n",
    "\n",
    "scaler = StandardScaler()\n",
    "X_train = scaler.fit_transform(X_train)\n",
    "X_test = scaler.transform(X_test)\n",
    "\n",
    "models = {\n",
    "    \"Logistic Regression\": LogisticRegression(max_iter=1000),\n",
    "    \"Random Forest\": RandomForestClassifier(random_state=42),\n",
    "    \"XGBoost\": XGBClassifier(eval_metric=\"logloss\", random_state=42)\n",
    "}\n",
    "\n",
    "metrics = {}\n",
    "\n",
    "for name, model in models.items():\n",
    "    model.fit(X_train, y_train)\n",
    "    y_pred = model.predict(X_test)\n",
    "    y_prob = model.predict_proba(X_test)[:, 1]\n",
    "\n",
    "    metrics[name] = {\n",
    "        \"Accuracy\": accuracy_score(y_test, y_pred),\n",
    "        \"Precision\": precision_score(y_test, y_pred),\n",
    "        \"Recall\": recall_score(y_test, y_pred),\n",
    "        \"F1\": f1_score(y_test, y_pred),\n",
    "        \"ROC-AUC\": roc_auc_score(y_test, y_prob),\n",
    "    }\n",
    "\n",
    "    cm = confusion_matrix(y_test, y_pred)\n",
    "    plt.figure(figsize=(4, 3))\n",
    "    sns.heatmap(cm, annot=True, fmt=\"d\", cmap=\"Blues\")\n",
    "    plt.title(name)\n",
    "    plt.xlabel(\"Predicted\")\n",
    "    plt.ylabel(\"Actual\")\n",
    "    plt.savefig(f\"confusion_matrix_{name.replace(' ', '_')}.png\")\n",
    "    plt.close()\n",
    "\n",
    "st.dataframe(pd.DataFrame(metrics).T.style.format(\"{:.4f}\"))\n",
    "\n",
    "# ================================\n",
    "# ANOMALY DETECTION\n",
    "# ================================\n",
    "st.header(\"🚨 Anomaly Detection\")\n",
    "\n",
    "iso = IsolationForest(random_state=42)\n",
    "df[\"IsAnomaly\"] = iso.fit_predict(X)\n",
    "df[\"IsAnomaly\"] = df[\"IsAnomaly\"].map({1: 0, -1: 1})\n",
    "\n",
    "st.metric(\"Detected Anomalies\", int(df[\"IsAnomaly\"].sum()))\n",
    "\n",
    "# ================================\n",
    "# DASHBOARDS\n",
    "# ================================\n",
    "st.header(\"📊 Interactive Dashboards\")\n",
    "\n",
    "tab1, tab2, tab3 = st.tabs([\"🌍 Geo Map\", \"📈 Activity Timeline\", \"📋 Dataset\"])\n",
    "\n",
    "with tab1:\n",
    "    fig = px.scatter_geo(\n",
    "        df[df[\"IsAnomaly\"] == 1],\n",
    "        lat=\"Latitude\",\n",
    "        lon=\"Longitude\",\n",
    "        hover_name=\"Username\",\n",
    "        title=\"Suspicious User Locations\"\n",
    "    )\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "with tab2:\n",
    "    fig = px.scatter(\n",
    "        df.sample(min(2000, len(df))),\n",
    "        x=\"LoginTimestamp\",\n",
    "        y=\"Username\",\n",
    "        color=\"IsFake\",\n",
    "        title=\"User Activity Timeline\"\n",
    "    )\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "with tab3:\n",
    "    st.dataframe(df, use_container_width=True)\n",
    "\n",
    "st.success(\"✅ Application loaded successfully\")\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
cd C:\Users\bhagg
streamlit run app.py

